# wrangler.toml for Cloudflare Pages deployment
name = "note-landing" # Set your Cloudflare Pages project name here or use variable
pages_build_output_dir = "./dist" # Output directory for TanStack Start build
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2024-05-05" # Use a recent date 

[observability]
enabled = true

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "note-app-version"