name = "note-landing"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2024-05-05"
main = ".output/server/index.mjs"
minify = true

[env.production]
routes = [{ pattern = "www.waitq.sh", custom_domain = true }]
name = "note-landing"
r2_buckets = [{ binding = "R2_BUCKET", bucket_name = "note-app-version" }]

[assets]
directory = "./.output/public/"

[observability]
enabled = true