name = "note-api"
main = "src/index.ts"
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat"]
minify = true

[vars]
LANDING_URL = "http://localhost:3000"
ELECTRON_URL = "http://localhost:5173"
DESKTOP_APP_PROTOCOL = "note-app"
BETTER_AUTH_URL = "http://localhost:8080"
NODE_ENV = "development"
BASE_DOMAIN = "localhost"
BYPASS_SUBSCRIPTION_CHECK = true

[[r2_buckets]]
binding = "RELEASE_BUCKET"
bucket_name = "note-app-version"

[env.production]
routes = [{ pattern = "api.waitq.sh", custom_domain = true }]
name = "qahwa-api"
r2_buckets = [{ binding = "RELEASE_BUCKET", bucket_name = "note-app-version" }]
upload_source_maps = true

[observability]
enabled = true

[env.production.vars]
LANDING_URL = "https://www.waitq.sh"
ELECTRON_URL = "http://localhost:5173"
DESKTOP_APP_PROTOCOL = "note-app"
BETTER_AUTH_URL = "https://api.waitq.sh"
BASE_DOMAIN = "waitq.sh"
NODE_ENV = "production"
BYPASS_SUBSCRIPTION_CHECK = false