name = "note-api"
main = "src/index.ts"
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat"]
minify = true

[dev]
port = 8080

[vars]
LANDING_URL = "http://localhost:3000"
ELECTRON_URL = "http://localhost:5173"
DESKTOP_APP_PROTOCOL = "note-app"
BETTER_AUTH_URL = "http://localhost:8080"

[env.production]
routes = [{ pattern = "api.waitq.sh", custom_domain = true }]
name = "note-api"


[env.production.vars]
LANDING_URL = "https://waitq.sh"
ELECTRON_URL = "http://localhost:5173"
DESKTOP_APP_PROTOCOL = "note-app"
BETTER_AUTH_URL = "https://api.waitq.sh"
