name: Deploy Web Apps

on:
  push:
    branches:
      - main
    paths: # Workflow runs if EITHER API OR LANDING changes
      - 'apps/api/**'
      - 'apps/landing/**'

jobs:
  check-changes:
    name: Check for Changed Files
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.changed_files_api.outputs.any_changed }}
      landing_changed: ${{ steps.changed_files_landing.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for tj-actions/changed-files to diff correctly

      - name: Get changed files for API
        id: changed_files_api
        uses: tj-actions/changed-files@v44 # Using a specific version is good practice
        with:
          files: apps/api/**

      - name: Get changed files for Landing
        id: changed_files_landing
        uses: tj-actions/changed-files@v44
        with:
          files: apps/landing/**

  deploy-api:
    name: Deploy API to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production # Add this to access environment variables
    needs: check-changes # Depends on the check-changes job
    if: needs.check-changes.outputs.api_changed == 'true' # Run only if API files changed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install API Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/api'
          command: deploy --minify --env production --config wrangler.toml

  deploy-landing:
    name: Deploy Landing Page to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production # Add this to access environment variables
    needs: check-changes # Depends on the check-changes job
    if: needs.check-changes.outputs.landing_changed == 'true' # Run only if landing files changed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Landing App Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Landing Page
        env:
          NODE_ENV: production
          VITE_APP_URL: '${{ vars.LANDING_URL }}'
          VITE_API_URL: '${{ vars.API_URL }}'
          VITE_DESKTOP_PROTOCOL: '${{ vars.DESKTOP_PROTOCOL }}'
          VITE_RELEASE_S3_ENDPOINT: '${{ vars.PUBLIC_R2_URL }}'
        run: |
          cd apps/landing
          pnpm run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/landing'
          command: deploy --minify --env production --config wrangler.toml